import type { AircraftProfile, FlightPlanInput } from './types'

export const aircraftProfiles: AircraftProfile[] = [
  {
    registration: 'SE-KBT',
    typeName: 'C172',
    callsign: 'Kilo Bravo Tango',
    cruiseTasKt: 102,
    fuelBurnLph: 32,
    fuelDensityKgPerLiter: 0.72,
    emptyWeightKg: 735,
    emptyMomentKgMm: 251370,
    armsMm: {
      frontLeft: 940,
      frontRight: 940,
      rearLeft: 1830,
      rearRight: 1830,
      baggage: 2480,
      fuel: 1210,
    },
    limits: {
      maxTowKg: 1110,
      minArmMm: 910,
      maxArmMm: 1220,
    },
    performance: {
      takeoff50FtM: 485,
      landing50FtM: 410,
    },
  },
  {
    registration: 'SE-MEP',
    typeName: 'PA-28',
    callsign: 'Mike Echo Papa',
    cruiseTasKt: 108,
    fuelBurnLph: 34,
    fuelDensityKgPerLiter: 0.72,
    emptyWeightKg: 702,
    emptyMomentKgMm: 242000,
    armsMm: {
      frontLeft: 910,
      frontRight: 910,
      rearLeft: 1810,
      rearRight: 1810,
      baggage: 2360,
      fuel: 1180,
    },
    limits: {
      maxTowKg: 1057,
      minArmMm: 880,
      maxArmMm: 1180,
    },
    performance: {
      takeoff50FtM: 510,
      landing50FtM: 430,
    },
  },
]

export const initialFlightPlan: FlightPlanInput = {
  aircraftRegistration: 'SE-KBT',
  header: {
    date: new Date().toISOString().slice(0, 10),
    departureAerodrome: 'ESSB',
    destinationAerodrome: 'ESNQ',
    captain: 'A. Martensson',
    observer: 'Spanare',
    notamStatus: 'Kontrollerad',
    weatherStatus: 'METAR/TAF',
    fplStatus: 'Aktiv',
    dailyInspection: 'Utförd',
    blockOut: '09:00',
    takeoff: '',
    landing: '',
    blockIn: '',
  },
  routeLegs: [
    {
      from: { name: 'Bromma', lat: 59.3544, lon: 17.941 },
      to: { name: 'Uppsala', lat: 59.8586, lon: 17.6389 },
      windDirection: 220,
      windSpeedKt: 15,
      tasKt: 102,
      variation: 6,
      altitude: '2500',
      navRef: 'UPP',
      notes: 'Utpassage norr',
    },
    {
      from: { name: 'Uppsala', lat: 59.8586, lon: 17.6389 },
      to: { name: 'Gävle', lat: 60.5933, lon: 17.4594 },
      windDirection: 230,
      windSpeedKt: 18,
      tasKt: 102,
      variation: 6,
      altitude: '3000',
      navRef: 'GVE',
      notes: '',
    },
    {
      from: { name: 'Gävle', lat: 60.5933, lon: 17.4594 },
      to: { name: 'Söderhamn', lat: 61.2608, lon: 17.1014 },
      windDirection: 240,
      windSpeedKt: 16,
      tasKt: 102,
      variation: 6,
      altitude: '3500',
      navRef: 'SDH',
      notes: 'Kustlinje',
    },
  ],
  radioNav: Array.from({ length: 8 }, (_, index) => ({
    name: index === 0 ? 'Stockholm Radio' : 'Funktion',
    frequency: index === 0 ? '124.700' : 'Frekvens',
  })),
  performance: {
    availableTakeoffDistanceM: 800,
    availableLandingDistanceM: 820,
    aerodromeElevationFt: 47,
    temperatureC: 18,
    runwaySurface: 'Asfalt',
    runwayCondition: 'Torr',
    headwindKt: 8,
  },
  fuel: {
    reserveMinutes: 45,
    extraOnBoardLiters: 8,
  },
  weightBalance: {
    frontLeftKg: 84,
    frontRightKg: 78,
    rearLeftKg: 0,
    rearRightKg: 72,
    baggageKg: 18,
  },
}
